### ISSUE TITLE
oasis-chain: Define funded accounts at cli

### ISSUE THREAD

**Issue by nhynes** [oasislabs/oasis-chain#29]
@ryscheng-bot[bot] commented on [Wed Jul 17 2019](https://github.com/oasislabs/private-devex/issues/2)

*@armaniferrante commented on Jul 10, 2019, 8:22 PM UTC:*

Right now the oasis-chain prefunds a couple of mnemonics. We should probably allow users to specify the mnemonics and/or accounts that they want funded to give them more flexibility.

*This issue was moved by [willscott](https://github.com/willscott) from [oasislabs/private-issues#508](https://github.com/oasislabs/private-issues/issues/508).*

**Comment by peterjgilbert** [comment]
Dup of #24
