### ISSUE TITLE
Compilation fails with most recent oasis-parity. 

### ISSUE THREAD

**Issue by kaimast** [oasislabs/oasis-chain#65]
**Steps to reproduce**
1. clone repository
2. run cargo install

**Expected behaviour**
Project compiles and installs without errors.

**Additional information**
Compilation error:
```
error[E0050]: method `encrypt_storage_value` has 2 parameters but the declaration in trait `ethcore::vm::ConfidentialCtx::encrypt_storage_value` has 3
    --> src/confidential/confidential_ctx.rs:226:30
       |
   226 |     fn encrypt_storage_value(&mut self, data: Vec<u8>) -> Result<Vec<u8>> { 
       |                              ^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters, found 2
       |
       = note: `encrypt_storage_value` from trait: `fn(&mut Self, std::vec::Vec<u8>, std::vec::Vec<u8>) -> std::result::Result<std::vec::Vec<u8>, ethcore::vm::Error>`
```

I think this commit broke it: https://github.com/oasislabs/oasis-parity/commit/a74eb3a367ea291da1620727f1148ed7ee47da61

To prevent issues like this in the future, I think your `Cargo.toml` should not refer to an active branch of oasis-parity but to a specific version/tag.

**Comment by kaimast** [comment]
Compiling the `v0.1.0` of `oasis-chain` produces the same error.

**Comment by nhynes** [comment]
thanks for discovering this issue! I'll post a fix shortly. In the meantime, I believe that if you build with `--locked`, it'll use the previous version, as specified in the lockfile.

**Comment by kaimast** [comment]
Thanks for fixing this so quickly, Nick!
